### ISSUE TITLE
Segmentation fault for `Font(fontbuffer=object())`

### ISSUE THREAD

**Issue by user202729** [pymupdf/PyMuPDF#838]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
```fitz.Font(fontbuffer=object())``` causes a segmentation fault.

## To Reproduce (mandatory)
See above.

## Expected behavior (optional)
It should raise a `TypeError` or something.

## Your configuration (mandatory)
Python 3.9.1, wheel.

## Additional context (optional)
This is not how the library is supposed to be used, but mistakes can happen (for example pass a `fontTools.TTFont` object in), and segmentation faults are annoying in Python (normally it would print a traceback and let the user catch it)

To generalize, perhaps there should be some way to make the functions that take `AnyType` arguments safe from user errors?

**Comment by user202729** [comment]
Looks like that normally there's a check, but in this case it's missing.

The straight forward fix would be

```
--- a/fitz/helper-stext.i
+++ b/fitz/helper-stext.i
@@ -830,6 +830,7 @@ fz_font *JM_get_font(fz_context *ctx,
         // fontbuffer
         have_buffer:;
         res = JM_BufferFromBytes(ctx, fontbuffer);
+        if (!res) THROWMSG(gctx, "bad type: 'fontbuffer'");
         font = fz_new_font_from_buffer(ctx, NULL, res, index, 0);
         goto fertig;
 ```

but in this case it raises a warning (also is there a memory leak?)

**Comment by JorjMcKie** [comment]
Thanks for spotting this.
Yes, this case is a left-over from the time when the `Font` class was introduced.
I have already corrected it in my local version.

**Comment by JorjMcKie** [comment]
I usually use a macro `EXISTS`, which checks for NULL and Python-True.

**Comment by malizheng** [comment]
I also encountered a similar error. When encountering this "Segmentation fault: 11" exception, "try: except:" cannot recognize this exception, and the program will exit abnormally. Is there any other way to identify this kind of exception in python?

**Comment by JorjMcKie** [comment]
>  Is there any other way to identify this kind of exception in python?

No - and that exactly is the problem - the Python interpreter itself is brought down. 
For every such incident, please submit an issue and **_material to reproduce the error_**.
I am able to test stuff under Windows and Linux (only) - not MAC OSX.

**Comment by user202729** [comment]
There's `faulthandler` to print a traceback on segmentation fault -- nevertheless, it's never possible to catch the error. -- since *this* error is not fixed, it might be the same (or related) error.

**Comment by JorjMcKie** [comment]
Fixed by v1.18.7, currently being uploaded.
